In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns

In [4]:
import statistics as stat

## Mean

In [20]:
data = [1,1,2,3,4,4,5,5,6,7,7,7,8,8,8,9,9,10]
print("Mean : ",sum(data)/len(data))

Mean :  5.777777777777778


In [22]:
stat.mean(data)

5.777777777777778

In [7]:
df = sns.load_dataset("mpg")

In [44]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [45]:
stat.mean(df["mpg"])

23.514572864321607

In [46]:
stat.mean(df["weight"])

2970.424623115578

In [47]:
stat.mean(df["horsepower"])

nan

In [48]:
df["horsepower"].unique()

array([130., 165., 150., 140., 198., 220., 215., 225., 190., 170., 160.,
        95.,  97.,  85.,  88.,  46.,  87.,  90., 113., 200., 210., 193.,
        nan, 100., 105., 175., 153., 180., 110.,  72.,  86.,  70.,  76.,
        65.,  69.,  60.,  80.,  54., 208., 155., 112.,  92., 145., 137.,
       158., 167.,  94., 107., 230.,  49.,  75.,  91., 122.,  67.,  83.,
        78.,  52.,  61.,  93., 148., 129.,  96.,  71.,  98., 115.,  53.,
        81.,  79., 120., 152., 102., 108.,  68.,  58., 149.,  89.,  63.,
        48.,  66., 139., 103., 125., 133., 138., 135., 142.,  77.,  62.,
       132.,  84.,  64.,  74., 116.,  82.])

In [8]:
mask = df["horsepower"].isnull()

In [9]:
mask.unique()

array([False,  True])

In [10]:
df = df[~mask]

In [11]:
df["horsepower"].unique()

array([130., 165., 150., 140., 198., 220., 215., 225., 190., 170., 160.,
        95.,  97.,  85.,  88.,  46.,  87.,  90., 113., 200., 210., 193.,
       100., 105., 175., 153., 180., 110.,  72.,  86.,  70.,  76.,  65.,
        69.,  60.,  80.,  54., 208., 155., 112.,  92., 145., 137., 158.,
       167.,  94., 107., 230.,  49.,  75.,  91., 122.,  67.,  83.,  78.,
        52.,  61.,  93., 148., 129.,  96.,  71.,  98., 115.,  53.,  81.,
        79., 120., 152., 102., 108.,  68.,  58., 149.,  89.,  63.,  48.,
        66., 139., 103., 125., 133., 138., 135., 142.,  77.,  62., 132.,
        84.,  64.,  74., 116.,  82.])

In [69]:
stat.mean(df["horsepower"])

104.46938775510205

## Median

In [5]:
data = {1,2,3,4,5,6,7,50}
stat.mean(data)

9.75

In [6]:
stat.median(data)

4.5

In [13]:
stat.median(df["horsepower"])

93.5

## Mode

In [14]:
stat.mode(data)

1

In [15]:
stat.mode(df["horsepower"])

150.0

In [16]:
df.mode()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  13.0        4.0          97.0       150.0  1985.0          14.5   
1   NaN        NaN           NaN         NaN  2130.0           NaN   
2   NaN        NaN           NaN         NaN     NaN           NaN   

   model_year origin            name  
0        73.0    usa     amc matador  
1         NaN    NaN      ford pinto  
2         NaN    NaN  toyota corolla