In [1]:
import numpy as np

In [22]:
arr1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr2 = np.array([[9,8,7],
                [6,5,4],
                [3,2,1]])
arr3 = np.array([[9,8,7,4],
                [6,5,4,2],
                [3,2,1,5]])

In [4]:
print(arr1 + arr2)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [6]:
# print(arr1 + arr3) gives an error

NameError: name 'arr3' is not defined

In [7]:
print(arr1 * arr2)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [11]:
print(arr1.dot(arr2)) # the dot operation => 1*9 + 2*6 + 3*3

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [13]:
print(arr2.dot(arr1))

[[ 90 114 138]
 [ 54  69  84]
 [ 18  24  30]]


 ## Indenxing and Slicing of array

In [25]:
arr = np.array([1,2,3,4,5])

In [16]:
print(arr[0],arr[4],arr[2])

1 5 3


In [20]:
print(arr[:-1])
print(arr[::-1])
print(arr[2:-2]) 
print(arr[0:])

[1 2 3 4]
[5 4 3 2 1]
[3]
[1 2 3 4 5]


In [23]:
arr1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [29]:
print(arr1[0][0])
print(arr1[:,:]) #the first : is used for rows and second is used for columns
print(arr1[:])

1
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
print(arr1[:,:1])

[[1]
 [4]
 [7]]


In [40]:
print(arr1[:1,:])

[[1 2 3]]


In [34]:
print(arr1[1:,:1])

[[4]
 [7]]


In [35]:
print(arr1[:1,:1])

[[1]]


In [36]:
print(arr1[:,:-1])

[[1 2]
 [4 5]
 [7 8]]


In [37]:
print(arr1[:,::-1])

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [38]:
print(arr1[::-1,:])

[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [39]:
print(arr1[::-1,::-1])

[[9 8 7]
 [6 5 4]
 [3 2 1]]
