In [1]:
import numpy as np

In [3]:
lst = [1,2,3,4,5,6]
arr = np.array(lst)
print(lst)
print(arr)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [6]:
print(sum(lst))
print(sum(arr))

21
21


## Adding value to all elements in the aray

In [12]:
arr + 2  # here arr is not updated
print(arr)
print(arr+2)
print(arr*2)
print(arr/2)
print(arr-2)
print(arr**2)

arr += 1 #arr = arr + 1. this will update the array
print(arr)

[1 2 3 4 5 6]
[3 4 5 6 7 8]
[ 2  4  6  8 10 12]
[0.5 1.  1.5 2.  2.5 3. ]
[-1  0  1  2  3  4]
[ 1  4  9 16 25 36]
[2 3 4 5 6 7]


## Max and Min from array

In [13]:
print(arr.max())
print(arr.min())

7
2


### from multi-D array

In [14]:
arr1 = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [16]:
print(arr1.max())
print(arr1.min())

9
1


In [26]:
print(arr1.max(axis = 0)) # axis refers to col and rows for multi dimentional array
print(arr1.max(axis = 1)) # 0 represents col and 1 represents row
print(arr1.min(axis = 0))
print(arr1.min(axis = 1))

[7 8 9]
[3 6 9]
[1 2 3]
[1 4 7]


In [27]:
print(sum(arr1))
print(arr1.sum())

[12 15 18]
45
