In [1]:
import numpy as np

In [3]:
lst = [1,2,3,4,5,6,7,8,9,10]

#write a prg to see how many elements are > 5
count = 0
for i in lst:
    if i>5:
        count += 1
print(count)

5


In [5]:
arr = np.array(lst)

arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [6]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [7]:
len(arr[arr > 5])

5

In [8]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[arr % 2 == 0]

array([ 2,  4,  6,  8, 10])