In [2]:
import numpy as np

In [3]:
np

<module 'numpy' from 'C:\\Users\\aryan\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

In [4]:
lst = [1,2,3]
lst

[1, 2, 3]

In [7]:
arr = np.array(lst)
type(arr)

numpy.ndarray

In [9]:
print(arr) #prints same as a list

[1 2 3]


In [10]:
arr.ndim  # shows dimensions of array

1

In [12]:
lst = [[1,2,3],
       [4,5,6],
       [7,8,9]]
arr1 = np.array(lst)
print(arr1.ndim)
print(arr1)


2
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
arr1.shape

(3, 3)

In [14]:
arr1.size

9

In [15]:
arr.dtype

dtype('int32')

In [16]:
zeroMatrix = np.zeros((5,4)) # creates an array containing all zeros
print(zeroMatrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
identityMatrix = np.ones((3,4)) # creates an array containing all ones
print(identityMatrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
import numpy as np

In [12]:
c = np.array([6,7,5,8])
d = np.array([4,3,7,8])
c.dot(d)


144