In [1]:
import numpy as np

In [14]:
np.random.random() # generates random number

0.8791903627997764

In [15]:
if np.random.random() > 0.5:
    print("Hello")
else:
    print("No Hello")

Hello


In [16]:
arr = np.random.random((3,3))
arr

array([[0.19711661, 0.08114008, 0.91667551],
       [0.27649912, 0.72225727, 0.94315619],
       [0.36113735, 0.62700981, 0.20011763]])

## Generating Array Range

In [17]:
arr1 = np.arange(1,10,2) #arange(start,end+1,difference)
print(arr1)

[1 3 5 7 9]


In [23]:
arr2 = np.linspace(1,2,5) #linespace(start,end+1,total values in array)
print(arr2)

[1.   1.25 1.5  1.75 2.  ]


## Reshape Array

In [27]:
arr = np.random.random((5,4))
print(arr)

[[0.17922596 0.78708489 0.95821835 0.95735878]
 [0.50374012 0.2550943  0.27452883 0.91183053]
 [0.15532508 0.35446962 0.23612324 0.49127401]
 [0.80756693 0.594609   0.79896905 0.62724986]
 [0.52155043 0.58226478 0.11426935 0.60855086]]


In [29]:
arr = np.reshape(arr, (2,10))  # the total elements must be same in reshape
print(arr) 

arr = np.reshape(arr, (20,1))
print(arr)

[[0.17922596 0.78708489 0.95821835 0.95735878 0.50374012 0.2550943
  0.27452883 0.91183053 0.15532508 0.35446962]
 [0.23612324 0.49127401 0.80756693 0.594609   0.79896905 0.62724986
  0.52155043 0.58226478 0.11426935 0.60855086]]
[[0.17922596]
 [0.78708489]
 [0.95821835]
 [0.95735878]
 [0.50374012]
 [0.2550943 ]
 [0.27452883]
 [0.91183053]
 [0.15532508]
 [0.35446962]
 [0.23612324]
 [0.49127401]
 [0.80756693]
 [0.594609  ]
 [0.79896905]
 [0.62724986]
 [0.52155043]
 [0.58226478]
 [0.11426935]
 [0.60855086]]


In [32]:
arr = np.random.random((2,3))
print(arr)
arr.flatten() #converts any dimension array into one-D array


[[0.8634043  0.27948174 0.0585099 ]
 [0.08029111 0.9328239  0.87703605]]


array([0.8634043 , 0.27948174, 0.0585099 , 0.08029111, 0.9328239 ,
       0.87703605])