In [1]:
import numpy as np

In [7]:
arr = np.array([[4,2,5,6,7],
         [8,1,3,7,2],
         [0,8,4,3,2]])

In [11]:
# arr.sort() this will sort only the rows of array 
np.sort(arr, axis = 1, kind='mergesort') #similar to above

array([[2, 4, 5, 6, 7],
       [1, 2, 3, 7, 8],
       [0, 2, 3, 4, 8]])

In [14]:
np.sort(arr, axis = 0, kind='quicksort') # sorts array elements column wise

array([[0, 1, 3, 3, 2],
       [4, 2, 4, 6, 2],
       [8, 8, 5, 7, 7]])

In [15]:
np.sort(arr)

array([[2, 4, 5, 6, 7],
       [1, 2, 3, 7, 8],
       [0, 2, 3, 4, 8]])

In [16]:
np.sort(arr,kind='heapsort')

array([[2, 4, 5, 6, 7],
       [1, 2, 3, 7, 8],
       [0, 2, 3, 4, 8]])

## decending order

In [2]:
arr = np.array((1,2,3,4,5))

In [6]:
np.sort(arr)[::-1]

array([5, 4, 3, 2, 1])