In [1]:
import numpy as np

In [2]:
arr1 = ([[1,2,3,4],[5,6,7,8]])
arr2 = ([[8,7,6,5],[4,3,2,1]])

## Concatenation array

### using hstack and vstack

In [4]:
np.vstack((arr1,arr2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [5]:
np.vstack((arr2,arr1))

array([[8, 7, 6, 5],
       [4, 3, 2, 1],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [6]:
np.hstack((arr1,arr2))

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

In [7]:
np.hstack((arr2,arr1))

array([[8, 7, 6, 5, 1, 2, 3, 4],
       [4, 3, 2, 1, 5, 6, 7, 8]])

### using concatenate

In [8]:
np.concatenate((arr1,arr2)) # by default axis = 0

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [9]:
np.concatenate((arr1,arr2),axis = 1)

array([[1, 2, 3, 4, 8, 7, 6, 5],
       [5, 6, 7, 8, 4, 3, 2, 1]])

### Concatination of muldi D array

In [5]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a,b),axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

## Splitting array

In [10]:
arr = np.concatenate((arr1,arr2))

In [11]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [12]:
np.hsplit(arr,2)

[array([[1, 2],
        [5, 6],
        [8, 7],
        [4, 3]]),
 array([[3, 4],
        [7, 8],
        [6, 5],
        [2, 1]])]

In [15]:
np.vsplit(arr,2) # np.vsplit(arr,3) gives error we can only split in equal parts

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[8, 7, 6, 5],
        [4, 3, 2, 1]])]

In [16]:
np.vsplit(arr,1)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [8, 7, 6, 5],
        [4, 3, 2, 1]])]

In [17]:
np.vsplit(arr,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[8, 7, 6, 5]]),
 array([[4, 3, 2, 1]])]

## column_stack

In [6]:
import numpy as np

In [9]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[6,5,4],[3,2,1]])
arr = np.column_stack([arr1,arr2])
print(arr)


[[1 2 3 6 5 4]
 [4 5 6 3 2 1]]


In [12]:
print(arr1[arr1 > 5])

[6]
